unique_ids:
  forms:
    Form1: DDIYBJ2J3MU776M5PMNTW5PXX4EZAM6O
  modules: {}
  server_modules:
    ServerModule1: '1706918063621896666319667.4694'
  assets:
    standard-page.html: WOT7AUW2MWW3ANBQV6ILW2CKIARWID7J
    theme.css: AOKOB4X5JCTRAHAJ2TTR4BHIXUNIW4PX
